config/routes.rb
Rails.application.routes.draw do
  resources :beer_clubs
  resources :memberships, only: [:index, :create, :delete]
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :show]
  delete 'ratings', to: 'ratings#destroy'
  resources :places, only: [:index, :show]
  resource :session, only: [:new, :create, :destroy]
  resource :membership, only: [:delete]
  resources :styles do
    get 'about', on: :collection
  end
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'toggle_account', on: :member
    get 'recommendations', on: :member
  end
  resources :memberships do
    post 'confirm', on: :member
  end

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'new_membership', to: 'memberships#new'
  post 'membership', to: 'memberships#create'
  get 'places', to: 'places#index'
  post 'places', to: 'places#search'
  delete 'membership', to: 'memberships#destroy'
  get 'beerlist', to:'beers#list'
  get 'calculator', to: "misc#calculator"
end

app/models/style.rb
class Style < ApplicationRecord
  has_many :beers
  has_many :ratings, through: :beers, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true

  include RatingAverage

  def average_rating
    rating_average(self)
  end

  def self.top(amount)
    Style.all.sort_by(&:average_rating).reverse.take(amount)
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :set_style, only: %i[show edit update destroy]

  def index
    @styles = Style.all
  end

  def about
    render partial: 'about'
  end

  def show
    if turbo_frame_request?
      render partial: 'details', locals: { style: @style }
    end
    @style = set_style
    @beers = @style.beers
  end

  def new
    @style = Style.new
  end

  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to style_url(@style), notice: "Style was successfully created." }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  def style_params
    params.require(:style).permit(:name, :description)
  end

  def set_style
    @style = Style.find(params[:id])
  end
end

app/views/styles/_about.html.erb
<%= turbo_frame_tag "about_style" do %>
  <div class="card">
    <p>Beer styles differentiate and categorise beers by colour, flavour, strength, ingredients, production method, recipe, history, or origin.</i>
    <p>The modern concept of beer styles is largely based on the work of writer Michael Jackson in his 1977 book The World Guide To Beer. In 1989, Fred Eckhardt furthered Jackson's work publishing The Essentials of Beer Style. Although the systematic study of beer styles is a modern phenomenon, the practice of distinguishing between different varieties of beer is ancient, dating to at least 2000 BC.</p>
    <p>What constitutes a beer style may involve provenance, local tradition, ingredients, aroma, appearance, flavour and mouthfeel. The flavour may include the degree of bitterness of a beer due to bittering agents such as hops, roasted barley, or herbs; and the sweetness from the sugar present in the beer.</p>
    <p>Source <a href="https://en.wikipedia.org/wiki/Beer_style">Wikipedia</a></p>
  </div>
<% end %>

app/views/styles/_details.html.erb
<%= turbo_frame_tag "style_details" do %>
  <h3><%= style.name %></h3>
  <p>
    <strong>Description:</strong>
    <%= style.description %>
  </p>

  <h4>beers</h4>

  <ul>
    <% @style.beers.each do |beer| %>
      <li>
        <%= link_to beer.name, beer %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/styles/_form.html.erb
<%= form_with(model: style) do |form| %>
  <% if style.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
        <% style.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/styles/index.html.erb
<h1>Styles</h1>

<div id="styles">
  <%= turbo_frame_tag "styles" do %>
    <% @styles.each do |style| %>
      <%= link_to style.name, style, data: { turbo_frame: "style_details" } %>
    <% end %>
  <% end %>

  <%= turbo_frame_tag "style_details" do %>
  <% end %>

</div>

<%= link_to "New style", new_style_path %>

<%= turbo_frame_tag "about_style" do %>
  <%= link_to "about", about_styles_path %>
<% end %>

app/views/styles/new.html.erb
<h1>New style</h1>

<%= render "form", style: @style %>

<br>

<div>
  <%= link_to "Back to styles", styles_path %>
</div>

app/views/styles/show.html.erb
<p>
  <strong>Name: </strong>
  <%= @style.name %>
</p>

<p>
  <strong>Description: </strong>
  <%= @style.description %>
</p>

<p>
  <strong>Beers:</strong>
  <ul>
    <% @beers.each do |beer| %>
      <li><%= beer.name %></li>
    <% end %>
  </ul>
</p>

<%= edit_and_destroy_buttons(@style) %>